config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers =>  { :registrations => 'registrations' }

  resources :users

  resources :comments

  resources :reservations

  resources :clients

  get 'mysite/home'
  get 'reservations/new'
  get 'comments/index'

  root 'mysite#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #attr_accessor :lastname, :firstname, :middlename

=begin
private
  def user_params
    params.require(:user).permit(:lastname,:firstname,:middlename)
  end
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenter, :article)
    end
end

app/controllers/mysite_controller.rb
class MysiteController < ApplicationController
  def show

  end
  def home

  end

  def comments

  end
  def contact

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update).push(:lastname,:middlename, :firstname)
    devise_parameter_sanitizer.for(:sign_up).push(:lastname,:middlename, :firstname)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:fullname, :address, :email, :password, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mysite_helper.rb
module MysiteHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_area :article %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="well well4">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-5">
              <h3 class="like">*Comment List</h3>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="col-md-2"></div>
              <div class="col-md-8">
                <center>
                  <table class="table table-bordered">
                    <thead class="thead">
                    <tr>
                      <th class="text-center"><center>Commenter</center></th>
                      <th class="text-center"><center>Article</center></th>
                      <th class="text-center" colspan="3"><center>Action</center></th>
                    </tr>
                    </thead>

                    <tbody>
                    <% @comments.each do |comment| %>
                        <tr>
                          <td><%= comment.commenter %></td>
                          <td class="th1"><%= comment.article %></td>
                          <td><%= link_to 'Show', comment %></td>
                          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
                          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                    <% end %>
                    </tbody>
                  </table>
                  <br/>
                  <%= link_to 'New Comment', new_comment_path, class: 'btn btn-primary commentbtn' %>
                </center>
              </div>
              <div class="col-md-2"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amakan Online Reservation System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar anchor navbar-default">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="navbar-header">
                    <button class="navbar-toggle"
                        data-toggle="collapse"
                        data-target="#navbarToggle">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <img src="/assets/Amakan%20logo.png" class="nav-image"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <div class="collapse navbar-collapse" id="navbarToggle">
                            <ul class="nav navbar-nav navbar-right">
                              <%if signed_in?%>
                                <li class="list"><%= link_to 'Home', mysite_home_path  %></li>
                                <li class="list"><%= link_to 'Product', reservations_new_path  %></li>
                                <li class="list"><%= link_to '*Reservations', reservations_path  %></li>
                                <li class="list"><%= link_to 'Comments', comments_path  %></li>
                                <li class="dropdown list">
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">User Account <span class="caret"></span></a>
                                  <ul class="dropdown-menu" role="menu">
                                    <li><%=link_to current_user.email, edit_user_registration_path %></li>
                                    <li><%=link_to "Logout", destroy_user_session_path, method: :delete %></li>
                                  </ul>
                                </li>
                              <%else%>
                                  <li class="list"><%=link_to "Register", new_user_registration_path %></li>
                                  <li class="list"><%=link_to "Login", new_user_session_path %></li>
                              <%end%>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>
<%= yield %>
<footer class="footer">
    <div class="container">
        <center>
            <h3 class="text-muted">All Rights Reserved</h3>
            <h4>2015</h4>
        </center>
    </div>
</footer>

</body>
</html>

app/views/mysite/bulletin.html.erb
<%= render '.reservations/index.html.erb' %>

app/views/mysite/comments.html.erb
    <div class="container">
      <div class="col-md-6">
        <div class="well well-2">
          <h2>*Comment On Us!!</h2>
          <hr>
          <h3>Name: <input type="text" style="width: 300px"/><br><br></h3>
          <h3>Address: <input type="text" style="width: 300px"/><br><br></h3>
          <h3>Comment:</h3><br/><br/>
          <div class="form-group">

            <textarea class="form-control post-content" placeholder="Create a new comment..."></textarea>

          </div><br><br><br><br/>

          <button class="btn btn-primary pull-right">Submit</button>

        </div>
      </div>

      <div class="col-md-6">
        <div class="well well-2">
          <h3>*Comment List</h3>
          <hr>
          <div class="left">
            <h4 style="margin-left: 10px">Maria Reyna Ordaniza <a href="#" style="margin-left: 165px">View Comment</a></h4>
            <h5 style="margin-left: 100px; color: cornflowerblue">Alangalang Leyte</h5>
            <h4>Commented at: (the date and time)</h4>
            <h4>Updated at: (the date and time)</h4>
          </div>
          <br><br>
          <div class="left">
            <h4 style="margin-left: 10px">Maria Reyna Ordaniza <a href="#" style="margin-left: 165px">View Comment</a></h4>
            <h5 style="margin-left: 100px; color: cornflowerblue">Alangalang Leyte</h5>
            <h4>Commented at: (date and time)</h4>
            <h4>Updated at: (date and time)</h4>
          </div>

        </div>
      </div>
    </div>

    <footer class="footer">
      <div class="container">
        <center>
          <h3 class="text-muted">All Rights Reserved</h3>
          <h4>2015</h4>
        </center>
      </div>
    </footer>

app/views/mysite/contact.html.erb
    <div class="container">
      <!--<div class="row">-->
      <div class="col-md-6">
        <div class="well well-3">
          <h4>Locate Us!</h4>
          <hr>
          <img src="/assets/map.png" alt=""/>
          <br><br><br>
          <h4>Our Address: <p style="color: #000000; font-size: 25px">Palo Leyte</p></h4>
        </div>
      </div>

      <div class="col-md-6">
        <div class="well well-1">
          <h4>Like Us On.. <br><br>
            <img src="/assets/facebook.png" class="png" alt=""/> facebook.com/AmakanPh
          </h4>
        </div>
      </div>

      <div class="col-md-6">
        <div class="well well-1">
          <h4>Follow Us On.. <br><br>
            <img src="/assets/twitter.png" class="png" alt=""/> @AmakanPh
          </h4>
        </div>
      </div>

      <div class="col-md-6">
        <div class="well well-1">
          <h4>Email Us On.. <br><br>
            <img src="/assets/email.png" class="png" alt=""/> Amakan@gmail.com
          </h4>
        </div>
      </div>
      <!--</div>-->
    </div>

    <footer class="footer">
      <div class="container">
        <center>
          <h3 class="text-muted">All Rights Reserved</h3>
          <h4>2015</h4>
        </center>
      </div>
    </footer>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= current_user.firstname %>
    <%= f.text_field :fullname, :value => current_user.firstname, :type => "hidden" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <a >
      <%= f.submit href: '#myModal2', data_toggle: 'modal', class: 'send' %>
    </a>

  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well well3">
        <h3 class="reservation">Reservation List .. .</h3>
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
            <div class="well table table-bordered">
              <table class=" table table-bordered">
                <thead>
                <tr>
                  <th class="text-center">Fullname</th>
                  <th class="text-center">Address</th>
                  <!--<th class="text-center">Email</th>-->
                  <!--<th class="text-center">Password</th>-->
                  <th class="text-center">Quantity</th>
                  <th class="text-center" colspan="3">Option</th>
                </tr>
                </thead>

                <tbody>
                <% @reservations.each do |reservation| %>
                    <tr>
                      <td><%= reservation.fullname %></td>
                      <td><%= reservation.address %></td>
                      <td><%= reservation.quantity %></td>
                      <td><%= link_to 'Show', reservation %></td>
                      <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
                      <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>

              <br>

              <%= link_to 'New Reservation', new_reservation_path %>
            </div>
          </div>
          <div class="col-md-1"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container con2">
  <div class="row row3">
    <div class="col-md-3">
      <div class="well">
        <div class="row">
          <img src="/assets/a.jpeg" class="product_image"/>
        </div>
        <div class="row row2">
          <p class="product_name">Product Name: Amakan_Design-1</p>
          <p class="product_price">Product Price: Php 380.00</p>
          <a href="#myModal" data-toggle="modal">Instructions to Reserve</a>
          <center>
            <a href="#myModal1" data-toggle="modal">
              <button class="btn btn-default btn-sm btn4">Make Your Reservation</button>
            </a>
          </center>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <div class="row">
          <img src="/assets/a1.jpeg" class="product_image"/>
        </div>
        <div class="row row2">
          <p class="product_name">Product Name: Amakan_Design-2:</p>
          <p class="product_price">Product Price: Php 350.00</p>
          <a href="#myModal" data-toggle="modal">Instructions to Reserve</a>
          <center>
            <a href="#myModal1" data-toggle="modal">
              <button class="btn btn-default btn-sm btn4">Make Your Reservation</button>
            </a>
          </center>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <div class="row">
          <img src="/assets/a2.jpeg" class="product_image"/>
        </div>
        <div class="row row2">
          <p class="product_name">Product Name: Amakan_Design-3 </p>
          <p class="product_price">Product Price: Php 360.00</p>
          <a href="#myModal" data-toggle="modal">Instructions to Reserve</a>
          <center>
            <a href="#myModal1" data-toggle="modal">
              <button class="btn btn-default btn-sm btn4">Make Your Reservation</button>
            </a>
          </center>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <div class="row">
          <img src="/assets/a3.jpeg" class="product_image"/>
        </div>
        <div class="row row2">
          <p class="product_name">Product Name: Amakan_Design-4</p>
          <p class="product_price">Product Price: Php 390.00 </p>
          <a href="#myModal" data-toggle="modal">Instructions to Reserve</a>
          <center>
            <a href="#myModal1" data-toggle="modal">
              <button class="btn btn-default btn-sm btn4">Make Your Reservation</button>
            </a>
          </center>
        </div>
      </div>
    </div>
  </div>
  <div class="row row4">
    <div class="col-md-3">
      <div class="well">
        <div class="row">
          <img src="/assets/a4.jpeg" class="product_image"/>
        </div>
        <div class="row row2">
          <p class="product_name">Product Name: Amakan_Design-5</p>
          <p class="product_price">Product Price: Php 390.00</p>
          <a href="#myModal" data-toggle="modal">Instructions to Reserve</a>
          <center>
            <a href="#myModal1" data-toggle="modal">
              <button class="btn btn-default btn-sm btn4">Make Your Reservation</button>
            </a>
          </center>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <div class="row">
          <img src="/assets/a5.jpeg" class="product_image"/>
        </div>
        <div class="row row2">
          <p class="product_name">Product Name: Amakan_Design-6</p>
          <p class="product_price">Product Price: Php 390.00</p>
          <a href="#myModal" data-toggle="modal">Instructions to Reserve</a>
          <center>
            <a href="#myModal1" data-toggle="modal">
              <button class="btn btn-default btn-sm btn4">Make Your Reservation</button>
            </a>
          </center>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <div class="row">
          <img src="/assets/a6.jpeg" class="product_image"/>
        </div>
        <div class="row row2">
          <p class="product_name">Product Name: Amakan_Design-7</p>
          <p class="product_price">Product Price: Php390.00</p>
          <a href="#myModal" data-toggle="modal">Instructions to Reserve</a>
          <center>
            <a href="#myModal1" data-toggle="modal">
              <button class="btn btn-default btn-sm btn4">Make Your Reservation</button>
            </a>
          </center>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <div class="row">
          <img src="/assets/a7.jpeg" class="product_image"/>
        </div>
        <div class="row row2">
          <p class="product_name">Product Name: Amakan_Design-8</p>
          <p class="product_price">Product Price: Php 410.00</p>
          <a href="#myModal" data-toggle="modal">Instructions to Reserve</a>
          <center>
            <a href="#myModal1" data-toggle="modal">
              <button class="btn btn-default btn-sm btn4">Make Your Reservation</button>
            </a>
          </center>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade"
       id="myModal" tabindex="-1"
       role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal">
            &times;
          </button>
          <h4 class="instructions">Instructions</h4>
        </div>
        <div class="modal-body">
          <ol class="instruction_list">
            <li>
              <p>Lorem ipsum dolor sit amet, consectetur
                adipisicingelit. Accusamus accusantium animi
                asperiores atque,aut consectetur consequatur
                doloremque ea earum eligendi excepturi harum
                illo inventore itaque omnis quos
                repellendus sapiente, tenetur!</p>
            </li>
            <li>
              <p>Lorem ipsum dolor sit amet, consectetur
                adipisicingelit. Accusamus accusantium animi
                asperiores atque,aut consectetur consequatur
                doloremque ea earum eligendi excepturi harum
                illo inventore itaque omnis quos
                repellendus sapiente, tenetur!</p>
            </li>
            <li>
              <p>Lorem ipsum dolor sit amet, consectetur
                adipisicingelit. Accusamus accusantium animi
                asperiores atque,aut consectetur consequatur
                doloremque ea earum eligendi excepturi harum
                illo inventore itaque omnis quos
                repellendus sapiente, tenetur!</p>
            </li>
            <li>
              <p>Lorem ipsum dolor sit amet, consectetur
                adipisicingelit. Accusamus accusantium animi
                asperiores atque,aut consectetur consequatur
                doloremque ea earum eligendi excepturi harum
                illo inventore itaque omnis quos
                repellendus sapiente, tenetur!</p>
            </li>
            <li>
              <p>Lorem ipsum dolor sit amet, consectetur
                adipisicingelit. Accusamus accusantium animi
                asperiores atque,aut consectetur consequatur
                doloremque ea earum eligendi excepturi harum
                illo inventore itaque omnis quos
                repellendus sapiente, tenetur!</p>
            </li>
          </ol>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary"
                  data-dismiss="modal">
            OK
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade"
       id="myModal1" tabindex="-1"
       role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal">
            &times;
          </button>
          <h4 class="reserve">New Reservation</h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-5">
              <img src="/assets/a.jpeg" class="product_image"/>
            </div>
            <div class="col-md-7">
              <%= render 'form' %>
            </div>
          </div>
        </div>
          <%= link_to 'Back', reservations_path %>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade"
       id="myModal2" tabindex="-1"
       role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal">
            &times;
          </button>
          <h4 class="reserve">Success :D</h4>
        </div>
        <div class="modal-body">
          <h3 class="tnx">
            Mr./Mrs. __________________ ,your request<br>
            has been successfully sent...<br/>
            Thank You!
          </h3>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary"
                  data-dismiss="modal">
            OK
          </button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @reservation.fullname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @reservation.address %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @reservation.quantity %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>